// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKgw7Y7wz-hmuIBSmyhdbAw2bYM8zG6cU',
    appId: '1:811640708019:android:5aef22ee5bc9b9184cc9c6',
    messagingSenderId: '811640708019',
    projectId: 'tworoomsample',
    storageBucket: 'tworoomsample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvpFh9Y08UE8MQcL6y6dkKZZ2xY_ptyrQ',
    appId: '1:811640708019:ios:4e20fe0e493732724cc9c6',
    messagingSenderId: '811640708019',
    projectId: 'tworoomsample',
    storageBucket: 'tworoomsample.appspot.com',
    androidClientId: '811640708019-4iq6e1c210ug6i34h6fckd7b336lfiqb.apps.googleusercontent.com',
    iosClientId: '811640708019-l6t46vabarfpoethmnk5eift19ijndoj.apps.googleusercontent.com',
    iosBundleId: 'com.missionyr.tworoom',
  );
}
